### ISSUE TITLE
Better camera look for anyone.

### ISSUE THREAD

**Issue by ghost** [JujuAdams/Ugg#13]
First thank you for this cool library it helped me on something I was working on...
Now let's jump to the code.

In the example project.

In `objCamera` `Create Event` I initialized a variable:
`hasFocus = false;`

Then in `objCamera` `Step Event` I replaced this code:
```game-maker-language
//If we've got the mouse locked...
if (mouseLock)
{
	//Figure out where the centre of the window is
	var _centreX = window_get_width()/2;
	var _centreY = window_get_height()/2;

	//Increment a timer. Once that timer reaches 5, start pitching/panning the camera
	//There's a little bit of lag between pressing F3 and the mouse actually
	//centring in the window - this timer stops the camera freaking out!
	++mouseLockTimer;
	if (mouseLockTimer > 4)
	{
		var _dX = window_mouse_get_x() - _centreX;
		var _dY = window_mouse_get_y() - _centreY;
		camYaw   -= 0.1*_dX;
		camPitch -= 0.1*_dY;
        
		camPitch = clamp(camPitch, -89, 89); //Make sure we can't gimbal lock the camera
	}

	//Now move the mouse
	window_mouse_set(_centreX, _centreY);
}
```
With this:
```game-maker-language
// If we've got the mouse locked...
if (mouseLock) // Improved mouseLock code.
{
	// Figure out where the centre of the window is.
	var _centreX = window_get_width() / 2;
	var _centreY = window_get_height() / 2;

	// Increment a timer. Once that timer reaches 5, start pitching/panning the camera
	// There's a little bit of lag between pressing F3 and the mouse actually
	// centring in the window - this timer stops the camera freaking out!
	++mouseLockTimer;
	if (mouseLockTimer > 11) // Why 11? because the game speed is 144.
	{
		var _dX = window_mouse_get_x() - _centreX;
		var _dY = window_mouse_get_y() - _centreY;
		if (window_has_focus())
		{
			if (!hasFocus) // If not focus then center the mouse and focus again.
			{
				window_mouse_set(_centreX, _centreY);
				hasFocus = true;
			}
			else
			{
				camYaw -= 0.1 * _dX;
				camPitch -= 0.1 * _dY;
			}
		}
		else // If window not focused then reset the lock timer and stop cam yaw/pitch to step.
		{
			hasFocus = false;
			mouseLockTimer = 0;
		}

		camPitch = clamp(camPitch, -89, 89); // Make sure we can't gimbal lock the camera.
	}

	// Now move the mouse.
	window_mouse_set(_centreX, _centreY);
}
```

# What was the issue?
When mouseLock is true and make the window unfocused like pressing windows key (Windowed mode).
The camera start freaking out until you make it focused again so with my new method now it fixed!

I just wanted to help that's it and I hope it really useful.

Best Regards -DevTRUCKer 😊

**Comment by ghost** [comment]
Oh, sorry I said (Windowed mode)! it also fixes (Fullscreen mode) too 😅

**Comment by ghost** [comment]
Hey I found a better way using delta time like so:
`if (mouseLockTimer > 4 * game_get_speed(gamespeed_fps) / 1000000 * delta_time)`

Now whatever the game speed is it will work perfectly.

Also you can use `var` if you want.

**Comment by JujuAdams** [comment]
Hokay gonna decline this PR because it's not relevant to the core functionality of the library. At some point I might make an example repo for various 3D things and I will use this PR as a reference for mouselook.

I would like to make some additional points that will help you make successful PRs in the future:

1. Title of this PR is unhelpful. PR titles should describe the nature of the adjustment, its scope, whether it's a fix to a functional issue etc.  Honestly the title comes across as a bit arrogant but I think that was accidental.
2. Ugg is a 3D primitives library. The camera code is a means to an end rather than a perfect catch-all solution.
3. It's unclear from your comments specifically what this PR addresses. It looks like it's coping with loss-of-focus and variable framerates. A good tip here is BLUF - "Bottom Line Up Front". Write the point of what you're communicating first _then_ describe why and how you came to that conclusion.
4. You appear to have use tabs instead of spaces which doesn't fit the formatting standard. Minor point but something to bear in mind for the future.

**Comment by ghost** [comment]
Thanks for the points also I love to improve codes even it's not related to the main library but it's fun XD
